# Generated by Django 5.1.3 on 2025-08-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_canceled'),
        ('store', '0010_order_total_amount_alter_order_phone_and_more'),
    ]

    operations = [
    ]
