# Generated by Django 5.1.3 on 2025-08-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Manually picked similar products', related_name='related_to', to='store.product'),
        ),
    ]
